Repository lola-tech/graphql-kimera, pull requests merged in 2020-04, with the labels that each got.

#1 chore: clean mirage lib
  packages/graphql-mirage/package.json
  packages/graphql-mirage/src/constants.js
  packages/graphql-mirage/src/engine.js
  packages/graphql-mirage/src/helpers.js
  packages/graphql-mirage/src/index.js
Labels: enhancement

#2 Adding doc files
  packages/graphql-mirage-docs/blog/2019-05-28-hola.md
  packages/graphql-mirage-docs/blog/2019-05-29-hello-world.md
  packages/graphql-mirage-docs/blog/2019-05-30-welcome.md
  packages/graphql-mirage-docs/docs/api-build-mocks.md
  packages/graphql-mirage-docs/docs/api-cache.md
  packages/graphql-mirage-docs/docs/api-get-executable-schema.md
  packages/graphql-mirage-docs/docs/api-merge-scenarios.md
  packages/graphql-mirage-docs/docs/data-sources.md
  packages/graphql-mirage-docs/docs/doc1.md
  packages/graphql-mirage-docs/docs/doc2.md
  packages/graphql-mirage-docs/docs/doc3.md
  packages/graphql-mirage-docs/docs/enums.md
  packages/graphql-mirage-docs/docs/field-name-builders.md
  packages/graphql-mirage-docs/docs/glossary.md
  packages/graphql-mirage-docs/docs/interfaces.md
  packages/graphql-mirage-docs/docs/introduction.md
  packages/graphql-mirage-docs/docs/mdx.md
  packages/graphql-mirage-docs/docs/mutations.md
  packages/graphql-mirage-docs/docs/object-type-builders.md
  packages/graphql-mirage-docs/docs/scalar-type-builders.md
  packages/graphql-mirage-docs/docs/scenarios.md
  packages/graphql-mirage-docs/docs/todo.md
  packages/graphql-mirage-docs/docs/tutorial-array-fields.md
  packages/graphql-mirage-docs/docs/tutorial-fields-repeating.md
  packages/graphql-mirage-docs/docs/tutorial-fields-with-args.md
  packages/graphql-mirage-docs/docs/tutorial-first-builder.md
  packages/graphql-mirage-docs/docs/tutorial-getting-started.md
  packages/graphql-mirage-docs/docs/tutorial-mutations.md
  packages/graphql-mirage-docs/docs/tutorial-scenarios.md
  packages/graphql-mirage-docs/docs/under-the-hood.md
  packages/graphql-mirage-docs/docusaurus.config.js
  packages/graphql-mirage-docs/package-lock.json
  packages/graphql-mirage-docs/sidebars.js
  packages/graphql-mirage-docs/src/pages/index.js
  packages/graphql-mirage-docs/static/img/logo-dark.png
  packages/graphql-mirage-docs/static/img/logo.png
  packages/graphql-mirage/package-lock.json
  packages/graphql-mirage/package.json
Labels: documentation, needs review

#12 fix: inconsistent sidebar navigation
  packages/graphql-mirage-docs/docs/enums.md
Labels: needs review
