Repository lola-tech/graphql-kimera, pull requests merged in 2020-06, with the labels that each got.

#68 feat: add global store support in query resolvers
  packages/graphql-kimera/package-lock.json
  packages/graphql-kimera/package.json
  packages/graphql-kimera/src/__test__/integration.test.js
  packages/graphql-kimera/src/__test__/testing.schema.graphql
  packages/graphql-kimera/src/engine.js
  packages/graphql-kimera/src/index.js
  packages/graphql-kimera/src/store.js
Labels: documentation, enhancement

#75 fix: return eligible assigned scenario falsy values
  packages/graphql-kimera/src/__test__/mockProviders.test.js
  packages/graphql-kimera/src/mockProviders.js
Labels: bug

#79 docs: fix store update method
  packages/graphql-kimera-docs/docs/mocking-mutations.md
Labels: documentation, needs review

#80 chore: wire up google analytics
  .github/workflows/gh-pages.yml
  packages/graphql-kimera-docs/docusaurus.config.js
Labels: needs review

#66 chore: draft of contributing guide
  .gitignore
  .yarnrc
  CONTRIBUTING.md
  README.md
  package-lock.json
  packages/graphql-kimera-docs/README.md
  packages/graphql-kimera-docs/package-lock.json
  packages/graphql-kimera/README.md
  packages/graphql-kimera/package-lock.json
  yarn.lock
Labels: needs review

#81 fix: Move graphql lib to peerDependecies
  .github/workflows/nodejs.yml
  README.md
  packages/graphql-kimera-docs/CHANGELOG.md
  packages/graphql-kimera-docs/README.md
  packages/graphql-kimera-docs/docs/setup.md
  packages/graphql-kimera-docs/package-lock.json
  packages/graphql-kimera-docs/package.json
  packages/graphql-kimera/CHANGELOG.md
  packages/graphql-kimera/README.md
  packages/graphql-kimera/package-lock.json
  packages/graphql-kimera/package.json
Labels: bug
